<?php
/**
 * PayPal Subscriptions
 * @var PayPal\Subscription\Block\Customer\View $block
 * @var PayPal\Subscription\Model\Subscription $subscription
 */

$subscription = $block->getSubscription();
$billingAddress = $subscription->getShippingAddress();
$shippingAddress = $subscription->getShippingAddress();
?>

<section class="block">

    <h3 class="block-title">
        <strong><?= $block->escapeHtml(__('Addresses')) ?></strong>
    </h3>

    <div class="block-content" data-bind="scope: 'defaultAddresses'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</section>

<script type="text/x-magento-init">
{
    "*": {
         "Magento_Ui/js/core/app": {
            "components": {
                "defaultAddresses": {
                    "component": "PayPal_Subscription/js/view/customer/addresses/default",
                    "billingAddress": "<?= $block->escapeJs($block->formatAddress($billingAddress)) ?>",
                    "shippingAddress": "<?= $block->escapeJs($block->formatAddress($shippingAddress)) ?>"
                }
            }
        }
    }
}

</script>